name: pi_python_opencv_confKafka

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build: 

    runs-on: pi_python_opencv_confKafka-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image for opencv along with confluent_kafka (python
      run: docker build . --file Dockerfile --tag pi_python_opencv_confKafka:$(date +%s)
