name: pi_opencv_confkafka

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest, arm-latest]
    runs-on: ${{ matrix.platform }}
  #build: 

    #runs-on: arm-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image for opencv along with confluent_kafka (python)
      run: docker build . --tag pi_opencv_confkafka:$(date +%s)
      env:
          HOST_NAME: Pi1
